Simplify and fix some issues with `#[component]` macro
DioxusLabs/dioxus pull request #2289
Opened 2024-04-10 15:59 UTC by tigerros

- Gets rid of a ton of code (almost half of the `component.rs` file + the 130 line long affectionately named `utils.rs` file), which wasn't even being used!! This is the doc building that I introduced in [1563](https://github.com/DioxusLabs/dioxus/pull/1563), and I'm sorry for introducing it. It's completely unnecessary because people can simply view the props struct through the `props` argument, and I don't know how it even got merged. Anyway, since then there have been some changes, and the original features made in [1563](https://github.com/DioxusLabs/dioxus/pull/1563) just didn't work. I tested it out and the macro simply would not build any docs. So there was a bunch of useless code, technically being used at compilation, but not being used at runtime. Or maybe it was being used somehow, slowing down compilation but not producing any results.
- Proper camel case allowing. This got removed at some point, don't know where, don't know why 🤷 AFAIK the convention is still `UpperCamelCase` for components, so I added it back. The reason I'm calling it "proper" is that it only allows non snake case identifiers for the function identifier, so it will still warn about other stuff like variables. Some previous implementations have applied `#[allow(non_snake_case)]` for the entire function, including the body, which would silence other stuff.
- Allow struct pattern parameter parsing (e.g. `fn Navbar(NavbarProps { title }: NavbarProps)`). This was previously being parsed incorrectly and the macro just wouldn't compile. I noticed this was used a lot in Freya which is probably why Freya doesn't use the `#[component]` macro, instead opting for putting `#[allow(non_snake_case)]` everywhere (which, as mentioned, is incorrect because it silences warnings of other identifiers).

2024-04-11 18:18 UTC, ealmloff commented
Expanding to a struct will cause lints on any components that use the `component_name` syntax with an underscore instead of upper camel case

2024-04-12 07:17 UTC, tigerros commented
> Expanding the component name to a struct will cause lints on any components that use the `component_name` syntax with an underscore instead of upper camel case

That's the point, since the convention is upper camel case and not snake case.

2024-04-26 16:07 UTC, jkelleyrtp commented
> > Expanding the component name to a struct will cause lints on any components that use the `component_name` syntax with an underscore instead of upper camel case
> 
> That's the point, since the convention is upper camel case and not snake case.

Love the fact that we're trimming the fat in this module - I was very confused by the complexity of it all last time I was digging around here.

Can we keep support for lowercase components? They're basically our unofficial syntax for wrapped web components. IE you'd wrap a stringly typed `kebab-case-element {}` with a `strongly_typed_element {}`.

We don't do anything differently with codegen there, per se, but it's a decent heuristic when glancing at code as to why those components are different.

2024-04-26 16:07 UTC, jkelleyrtp requested changes
Love the fact that we're trimming the fat in this module - I was very confused by the complexity of it all last time I was digging around here.

Can we keep support for lowercase components? They're basically our unofficial syntax for wrapped web components. IE you'd wrap a stringly typed kebab-case-element {} with a strongly_typed_element {}.

We don't do anything differently with codegen there, per se, but it's a decent heuristic when glancing at code as to why those components are different.

2024-04-26 18:21 UTC, tigerros commented
> Can we keep support for lowercase components? They're basically our unofficial syntax for wrapped web components. IE you'd wrap a stringly typed kebab-case-element {} with a strongly_typed_element {}.

Done. I just want to point out that they're definitely "supported", they will just trigger a warning (which you can easily suppress with `#[allow(non_camel_case_types)]`), not an error. I thought it made sense because camel case is the convention, but I guess I didn't consider web components.

2024-06-18 22:43 UTC, jkelleyrtp requested changes
Reviewing this now, sorry for the wait.

We want to keep lowercase component support, but also allow the new deconstructed props syntax.

Also I think keeping the extra props doc is nice - it helps with discovery on optional fields.

2024-06-18 22:43 UTC, jkelleyrtp commented on packages/core-macro/src/component.rs
> +            tokens.append_all(allow_camel_case_for_fn_ident(comp_fn).into_token_stream());
Let's keep this.

2024-06-18 22:43 UTC, jkelleyrtp commented on packages/core-macro/src/component.rs
> +            quote! { #struct_ident { #(#struct_field_names),* }: #struct_ident #impl_generics }
and this as well.

2024-06-18 22:43 UTC, jkelleyrtp commented on examples/rsx_usage.rs
> -
we want to keep lower_case component support without warnings.

2024-08-08 17:28 UTC, ealmloff approved these changes

2024-08-08 17:32 UTC, jkelleyrtp approved these changes

2024-08-08 18:00 UTC, merged