Add `Dioxus-cli` Document
DioxusLabs/dioxus pull request #269
Opened 2022-02-20 02:20 UTC by mrxiaozhuox

2022-02-24 10:42 UTC, mrxiaozhuox commented
@jkelleyrtp Please help me to check the grammar haha !

2022-02-24 12:25 UTC, BarryYan commented
@mrxiaozhuox Why not merge it into [Cli](https://github.com/dioxusLabs/cli) repo? :smiley:

2022-02-24 12:29 UTC, BarryYan commented on docs/cli/src/configure.md
> +2. ***script*** - include soe script(JS) file into html.
`soe` -> `some`

2022-02-24 15:34 UTC, mrxiaozhuox commented
> @mrxiaozhuox Why not merge it into [Cli](https://github.com/dioxusLabs/cli) repo? 😃

Because I think we need put all docs in `dioxus` repo.

2022-02-26 15:41 UTC, mrxiaozhuox commented
😃

2022-02-26 22:23 UTC, jkelleyrtp requested changes
Just some simple grammar stuff (plurals, capitalization)

2022-02-26 22:23 UTC, jkelleyrtp commented on docs/cli/src/cmd/build.md
> +`dioxsu build` command can help you `pack & build` a dioxus project.
dioxus

2022-02-26 22:23 UTC, jkelleyrtp commented on docs/cli/src/introduction.md
> +It include `dev server`, `hot reload` and some `quick command` to help you use dioxus.
include should be plural (includes)

2022-02-27 07:33 UTC, jkelleyrtp commented
Awesome - thank you!

We'll probably make some more tweaks to docs before releasing the next version.

2022-02-27 07:33 UTC, merged