feat(nodes): VNode iterating with NodeCursor
DioxusLabs/dioxus pull request #2722
Opened 2024-07-27 22:23 UTC by rhaskia

This is an implementation of NodeCursor for issue #1177. It's still a bit messy right now but it is mostly working

2024-08-02 20:01 UTC, jkelleyrtp requested changes
Thanks! Excited to have this!
A few things
- Our formatters have different line lengths and causing diffs in places there shouldn't be
- some methods don't check for panics which need to
- it's definitely feasible to implement traversing into children from components if the VirtualDom is captured somehow, might be a worthwhile addition

2024-08-02 21:42 UTC, rhaskia commented on packages/core/src/nodes.rs
> +                    DynamicNode::Component(_) => None,
How would I go about accessing the VirtualDom in here?

2024-08-02 21:43 UTC, rhaskia commented on packages/core/src/nodes.rs
> +impl IntoDynNode for NodeCursor {
Unsure really, was just there in the original issue

2024-08-02 22:37 UTC, rhaskia commented on packages/core/src/nodes.rs
> +        let item = self.clone();
I'll see if I can work it to be borrowed

2024-08-02 23:23 UTC, jkelleyrtp commented on packages/core/src/nodes.rs
> +                    DynamicNode::Component(_) => None,
Hmmmm, I think in some usecases there won't be a virtualdom, so maybe the &VirtualDom could be optional when creating the cursor.

Maybe we could add a field to `NodeCursor` that's `Option<&VirtualDom>` and traverse it if we have it?

Eventually I we want core to expose the root node of components via the `Runtime` object so the cursor can work without the virtualdom, but we're not currently set up for that.

For the usecases I want to use the cursor for I'd find the optional VirtualDom to be super useful (IE a new immediate mode renderer)

2024-08-02 23:46 UTC, rhaskia commented on packages/core/src/nodes.rs
> +                    DynamicNode::Component(_) => None,
Oh yes, I can set that up then. Maybe also some option to the root of the virtual dom instead of the VNode, or is that too much?

2024-08-03 21:43 UTC, rhaskia commented on packages/core/src/nodes.rs
> +        let item = self.clone();
Set this up with the new commit, though some of the accessing code might be incorrect. Not sure exactly how I would test the dynamic components.

2024-08-03 21:44 UTC, rhaskia commented on packages/core/src/nodes.rs
> +                    DynamicNode::Component(_) => None,
Set this up with the new commit, though some of the accessing code might be incorrect. Not sure exactly how I would test the dynamic components.

2024-08-08 18:22 UTC, ealmloff reviewed
I attached the good first issue tag on the issue associated with this PR, but the very general implementation of a walker this PR implements is more complex than I was expecting. The general version of the walker needs to walk a tree of trees. VNodes make a tree and each VNode itself is a tree of static and dynamic rsx.

A node walker would still be very useful, but it might not be the easiest place to start contributing to dioxus. The structure of nodes in core is slightly odd for performance reasons and less documented than most other crates in the repo

There are a few places where the walk will proceed to the wrong node because of the structure of templates. If you want to continue this PR, there is an explanation of the template structure [here](https://dioxuslabs.com/learn/0.5/contributing/walkthrough_readme#the-rsx-macro). We also traverse nodes in SSR [here](https://github.com/DioxusLabs/dioxus/blob/b97e607aca0bd8a12971fcf403908addf9a45dd7/packages/ssr/src/renderer.rs) which may be useful as a reference

2024-08-08 18:22 UTC, ealmloff commented on packages/core/src/nodes.rs
> +                        current = &children.get(child_index as usize)?.template.get().roots[0]
Dynamic nodes are always a leaf in the template subtree tree. If we reach a fragment, we need to traverse into the child VNode

2024-08-08 18:22 UTC, ealmloff commented on packages/core/src/nodes.rs
> +                        let scope = component.mounted_scope(0, self.inner, self.vdom?);
0 should by `id`, it is the dynamic node index

2024-08-08 18:22 UTC, ealmloff commented on packages/core/src/nodes.rs
> +            TemplateNode::Dynamic { .. } => None,
The dynamic node could point to text

2024-08-08 18:22 UTC, ealmloff commented on packages/core/src/nodes.rs
> +        position.push(0);
Just pushing a position here isn't enough because we might move into a child VNode depending on where we are in the tree

2024-08-08 18:22 UTC, ealmloff commented on packages/core/src/nodes.rs
> +        let sibling = NodeCursor { inner: self.inner, vdom: self.vdom, position };
Again, the VNode may change

2024-10-26 00:35 UTC, closed without merging