pin SWC again to fix cli building
DioxusLabs/dioxus pull request #2861
Opened 2024-08-19 21:19 UTC by jkelleyrtp

2024-08-20 17:26 UTC, DogeDark requested changes
Running `cargo update` at all will bump the minor version despite the inequality requirement. Is this expected?

2024-08-23 07:26 UTC, ed-li commented
`cargo update` is ignoring this pin because the swc_ecma_transforms_proposal dependency is for manganis/cli-support

swc (and swc_common) were pinned in DioxusLabs/manganis#60, but the original issue has since been resolved and swc@0.283.0 through 0.284.0 are incompatible with swc_ecma_transforms_proposal@0.178.1: swc-project/swc#9455

swc@0.284.1 fixes this: 238ba8b1d2220202129595185bd4411b9415cc99

2024-08-29 14:32 UTC, ealmloff approved these changes

2024-08-29 14:42 UTC, ealmloff commented
Fixed upstream in https://github.com/DioxusLabs/manganis/pull/67

2024-08-29 14:42 UTC, closed without merging